name: Création du Docker

# Ceci déclenche l'action à chaque fois que vous poussez du code sur la branche "main"
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Se connecter au registre GitHub (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construire et pousser l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # L'image portera le nom de votre dépôt, par exemple : ghcr.io/beluchon/co2nh:latest
          tags: ghcr.io/${{ github.repository }}:latest
